---
version: '3'

services:
  thredds-quickstart:
    image: unidata/thredds-docker:5.0-beta8
    ports:
      - "3002:8080"
      - "443:8443"
      - "8443:8443"

  thredds-production:
    image: unidata/thredds-docker:5.0-beta8
    ports:
      - "3002:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - ./logs/:/usr/local/tomcat/logs/
      - ./logs/:/usr/local/tomcat/content/thredds/logs/
      - ./files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./content/:/usr/local/tomcat/content/thredds/
      - ./data/:/usr/local/data/data/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

  tdm:
    image: unidata/tdm-docker:5.0-beta8
    container_name: tdm
    volumes:
      - ./content/:/usr/local/tomcat/content/thredds/
      - ./data/:/usr/local/data/
      # TDM logging non-configurable until 5.0 so you'll need tdm.sh and
      # tdm.jar if you want to log outside the container :-(
      - ./logs/:/usr/local/tomcat/content/tdm/
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
